### ISSUE TITLE
License to figure

### ISSUE THREAD

**Issue by jo-mueller** [clEsperanto/clesperanto.github.io#4]
Hi @haesleinhuepf ,

would it be ok for you if I used the cle logo in a presentation at a course about napari? This repository here doesn't have a license so I'd need your consent :) Thanks in advance!

**Comment by haesleinhuepf** [comment]
Feel free to use the logo. Furthermore, you find many slides about clesperanto here: 
https://f1000research.com/gateways/neubias?n0=text&v0=clesperanto&o0=&selectedDomain=slides

Those are all [CC-BY](https://creativecommons.org/licenses/by/4.0/) licensed. Thus, you're free to... 

![image](https://user-images.githubusercontent.com/12660498/225352965-7c8adaef-181b-4475-8bcb-67e271e9efb2.png)
